version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./.env
    networks:
      - "backend"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  redis:
    image: redis
    networks:
      - "backend"
    volumes:
      - "redis_data:/opt/redis/data"

  api:
    build: .
    env_file:
      - ./.env
    networks:
      - "backend"
    depends_on:
      - db
      - redis

volumes:
    redis_data:
    postgres_data:

networks:
  backend:
