version: "3.8"

services:
  nginx:
    build: ./nginx
    restart: always
    env_file:
      - ./.env
    networks:
      - "backend"
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - api

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - "backend"
    depends_on:
      - api

volumes:
    redis_data:
    postgres_data:

networks:
  backend:
